BATCH_SIZE: 6000
RESOLUTION: 256
DEVICE: "cuda:4"

PATHS:
  SAVE_EPOCH: "Contrastive_ES1_EPOCH.pth"

MAX_MINIBATCH_PROCESS: 500 #Must be divisible by SMALL_MINIBATCH
SMALL_MINIBATCH: 20

SPLIT: "Split-4" #One of: "ES1","ES2","ES3","ES4","ES5","Split-1","Split-2","Split-3","Split-4",

DATASET: "ForenSynths" #change it for "ForenSynths to use ForenSynths dataset"

EPOCHS: 1
